// Mocks generated by Mockito 5.0.17 from annotations
// in ui/test/widgets/vagas/desocupar_vaga_dialog_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i3;
import 'package:domain/estacionamento_raro_entities.dart' as _i9;
import 'package:domain/src/domain/errors/failure.dart' as _i8;
import 'package:domain/src/domain/repositories/vaga/vaga_repository.dart'
    as _i2;
import 'package:domain/src/domain/usecases/registro/create_registro_usecase.dart'
    as _i4;
import 'package:domain/src/domain/usecases/registro/update_horario_saida_usecase.dart'
    as _i5;
import 'package:domain/src/domain/usecases/vaga/close_vaga_usecase.dart'
    as _i10;
import 'package:domain/src/domain/usecases/vaga/get_vagas_usecase.dart' as _i6;
import 'package:domain/src/domain/usecases/vaga/open_vaga_usecase.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeVagaRepository_0 extends _i1.Fake implements _i2.VagaRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeCreateRegistroUseCase_2 extends _i1.Fake
    implements _i4.CreateRegistroUseCase {}

class _FakeUpdateHorarioSaidaUseCase_3 extends _i1.Fake
    implements _i5.UpdateHorarioSaidaUseCase {}

/// A class which mocks [GetVagasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVagasUseCase extends _i1.Mock implements _i6.GetVagasUseCase {
  MockGetVagasUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VagaRepository get vagaRepository =>
      (super.noSuchMethod(Invocation.getter(#vagaRepository),
          returnValue: _FakeVagaRepository_0()) as _i2.VagaRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, List<_i9.Vaga>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
          returnValue: Future<_i3.Either<_i8.Failure, List<_i9.Vaga>>>.value(
              _FakeEither_1<_i8.Failure, List<_i9.Vaga>>())) as _i7
          .Future<_i3.Either<_i8.Failure, List<_i9.Vaga>>>);
}

/// A class which mocks [CloseVagaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloseVagaUseCase extends _i1.Mock implements _i10.CloseVagaUseCase {
  MockCloseVagaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VagaRepository get vagaRepository =>
      (super.noSuchMethod(Invocation.getter(#vagaRepository),
          returnValue: _FakeVagaRepository_0()) as _i2.VagaRepository);
  @override
  _i4.CreateRegistroUseCase get createRegistroUseCase =>
      (super.noSuchMethod(Invocation.getter(#createRegistroUseCase),
              returnValue: _FakeCreateRegistroUseCase_2())
          as _i4.CreateRegistroUseCase);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.Vaga>> call(
          {String? vagaId, String? placa}) =>
      (super.noSuchMethod(
              Invocation.method(#call, [], {#vagaId: vagaId, #placa: placa}),
              returnValue: Future<_i3.Either<_i8.Failure, _i9.Vaga>>.value(
                  _FakeEither_1<_i8.Failure, _i9.Vaga>()))
          as _i7.Future<_i3.Either<_i8.Failure, _i9.Vaga>>);
}

/// A class which mocks [OpenVagaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenVagaUseCase extends _i1.Mock implements _i11.OpenVagaUseCase {
  MockOpenVagaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VagaRepository get vagaRepository =>
      (super.noSuchMethod(Invocation.getter(#vagaRepository),
          returnValue: _FakeVagaRepository_0()) as _i2.VagaRepository);
  @override
  _i5.UpdateHorarioSaidaUseCase get updateHorarioSaidaUseCase =>
      (super.noSuchMethod(Invocation.getter(#updateHorarioSaidaUseCase),
              returnValue: _FakeUpdateHorarioSaidaUseCase_3())
          as _i5.UpdateHorarioSaidaUseCase);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.Vaga>> call(
          {String? vagaId, String? registroId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #call, [], {#vagaId: vagaId, #registroId: registroId}),
              returnValue: Future<_i3.Either<_i8.Failure, _i9.Vaga>>.value(
                  _FakeEither_1<_i8.Failure, _i9.Vaga>()))
          as _i7.Future<_i3.Either<_i8.Failure, _i9.Vaga>>);
}
